import type { Secrets } from './secrets';

export interface EnvOptions {
  secrets: Secrets;
  /** Full DATABASE_URL; a placeholder is written when omitted. */
  databaseUrl?: string;
  appUrl?: string;
  port?: number;
}

const DEFAULT_DATABASE_URL =
  'postgresql://postgres:postgres@localhost:5432/authkit?schema=public';

/** Renders a ready-to-use server `.env` file with the given secrets. */
export function buildEnvFile(options: EnvOptions): string {
  const port = options.port ?? 4000;
  const appUrl = options.appUrl ?? 'http://localhost:5173';

  return `# Generated by @authkit/cli — do not commit this file.

NODE_ENV=development
PORT=${port}
CORS_ORIGINS=${appUrl}

DATABASE_URL=${options.databaseUrl ?? DEFAULT_DATABASE_URL}

JWT_ACCESS_SECRET=${options.secrets.jwtAccessSecret}
JWT_REFRESH_SECRET=${options.secrets.jwtRefreshSecret}
ENCRYPTION_KEY=${options.secrets.encryptionKey}

ACCESS_TOKEN_TTL=15m
REFRESH_TOKEN_TTL_DAYS=30

COOKIE_DOMAIN=localhost
COOKIE_SECURE=false

APP_URL=${appUrl}

EMAIL_VERIFICATION_TTL_HOURS=24
PASSWORD_RESET_TTL_MINUTES=30

# Leave SMTP_HOST blank to log emails to the console in development.
EMAIL_FROM=AuthKit Pro <no-reply@authkit.local>
SMTP_HOST=
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=
SMTP_PASS=

TOTP_ISSUER=AuthKit Pro
TRUSTED_DEVICE_TTL_DAYS=30

SERVER_PUBLIC_URL=http://localhost:${port}
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
`;
}
